# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: "192.168.33.30"

  config.vm.hostname = "winegram"

  config.vm.synced_folder "../shared/winegram",  "/home/vagrant/winegram", create: true

  config.vm.provision "shell", path: "scripts/install_modules.sh", args: "/vagrant/modules/"

  config.vm.provision "puppet" do |puppet|
    puppet.module_path    = "modules"
    puppet.manifests_path = "environments/development/manifests"
    puppet.manifest_file  = "site.pp"
  end
end
